// <auto-generated />
namespace SellYourStuff.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedcategoriestocategoryinproduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedcategoriestocategoryinproduct));
        
        string IMigrationMetadata.Id
        {
            get { return "201606030936425_changed categories to category in product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
